name = "GameTheory"
version = "0.1.0"
keywords = ["math", "game-theory"]
defaultTargets = ["GameTheory"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[lean_lib]]
name = "GameTheory"
